### ISSUE TITLE
min_separators() and is.separator() incorrect output

### ISSUE THREAD

**Issue by alexdeluca** [igraph/rigraph#242] opened 2017-12-01 14:02 UTC
`min_separators` and `is.separator` give incorrect output.
Example:
````
g <- graph(edges = c('A', 'B', 'B','C'))
plot(g)
min_separators(g) # should return B, empty list instead
is.separator(g, 'B') # correct
is.separator(g,'A') # correct
is.separator(g,c('A', 'C')) # incorrectly returns true.
````

**Comment by szhorvat** [comment] 2020-11-22 12:40
The corresponding issue for the C core (where this needs to be fixed): https://github.com/igraph/igraph/issues/1480

**Comment by szhorvat** [comment] 2022-04-01 13:09
I'll close this to reduce clutter in the R/igraph issue tracker. The problem is being tracked at https://github.com/igraph/igraph/issues/1480

**Closed by szhorvat** 2022-04-01 13:09 UTC
