### ISSUE TITLE
Strange graph operation

### ISSUE THREAD

**Issue by mrepetto94** [igraph/rigraph#488] opened 2021-11-06 16:35 UTC
The following example 

```
h1 <- graph_from_literal(1-2, 3-2)
h2 <- graph_from_literal(4-6, 4-7, 5-6, 6-7)
g <- union(h1,h2)

plot(g - edges(c(4, 6)))

```

Will result in a graph where 1 and 2 edges are cut. 1 and 2 labels are not indexed at positions 4 and 6.

**Comment by szhorvat** [comment] 2021-11-06 16:44
This is not a bug. The code you show removes the 4th and 6th edges. 

I assume you meant to remove edge `4-6`. You could retrieve the corresponding edge ID using `get.edge.ids(g,c("4","6"))` This returns `4`, as `4-6` is the 4th edge. Note that I used strings to refer to vertex _names_. If you use integers, as in `get.edge.ids(g,c(4,6))`, they will be interpreted as vertex _indices_. In this graph, vertex names and indices are not the same, see `V(g)$name`.

**Closed by szhorvat** 2021-11-06 16:44 UTC

**Comment by gaborcsardi** [comment] 2021-11-06 16:47
Another alternative to remove an edge using node names:

```r
g - path("4", "6")
```
