### ISSUE TITLE
Unable to install iGraph in Ubuntu 14.04 running R 3.3.2

### ISSUE THREAD

**Issue by PinakiGhosh** [igraph/rigraph#220] opened 2017-08-16 12:40 UTC
While trying to install iGraph via the command `install.packages('igraph')` I am getting the following error:
`foreign-graphml.c: In function ‘igraph_write_graph_graphml’:
foreign-graphml.c:1408:46: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "<graphml xmlns=\"" GRAPHML_NAMESPACE_URI "\"\n");
                                              ^
foreign-graphml.c:1412:59: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "         xsi:schemaLocation=\"" GRAPHML_NAMESPACE_URI "\n");
                                                           ^
foreign-graphml.c:1414:38: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "         " GRAPHML_NAMESPACE_URI "/1.0/graphml.xsd\">\n");
                                      ^
make: *** [foreign-graphml.o] Error 1
ERROR: compilation failed for package ‘igraph’`
Please let me know how to resolve this issue

**Comment by kosmoz** [comment] 2017-08-21 11:26
I am having the same issue installing from CRAN.

Installing from Github (using `devtools`) worked.

**Comment by shiosai** [comment] 2017-09-13 09:40
same problem here

**Comment by StephCarr** [comment] 2017-09-16 12:59
I'm also having the same issue. Using Ubuntu and R 3.3.2

**Comment by StephCarr** [comment] 2017-09-16 13:10
Yep, Installing using devtools worked for me too

**Comment by gaborcsardi** [comment] 2017-09-21 09:03
Duplicate of #213.

**Closed by gaborcsardi** 2017-09-21 09:03 UTC
