### ISSUE TITLE
Compilation failed on Cent OS

### ISSUE THREAD

**Issue by smichard** [igraph/rigraph#231] opened 2017-10-17 09:34 UTC
Hello,

I have an issue installing the igraph package 1.1.2 on Cent OS 7. Please find a Dockerfile below describing the steps I tried to install the package.

With option 1 I tried to install the igraph package from CRAN.
With option 2 I tried to install it from source. The package is placed in the packages folder
Both options fail to install the package and terminated with the error message “ERROR: compilation failed for package ‘igraph’ …”.

Any hints? Am I missing a package which is needed as a prerequisite?

Best

Stephan

```
FROM centos:7

# Installing Cent OS packages
RUN yum -y update && yum -y install \
	epel-release \
	java-1.8.0-openjdk \
	java-1.8.0-openjdk-devel \
	libapreq2-devel \
	libcurl-devel \
	libpng-devel \
	libtiff-devel \
	libjpeg-turbo-devel \
	yum-utils && \
	yum clean all

# Installing R
RUN yum -y update && yum -y install \
	R

# Copy Packages	
COPY ./packages /packages

# Installing R-Shiny and R packages
RUN	R -e "install.packages('shiny', repos='http://cran.rstudio.com/')" && \
	yum -y install --nogpgcheck /packages/shiny-server-1.5.3.838-rh5-x86_64.rpm && \
	R -e "install.packages(c('ape', 'broom', 'compiler', 'digest', 'dplyr', 'flexdashboard', 'forcats', 'GGally', 'ggplot2', 'graph', 'igraphdata', 'irlba', 'maps', 'magrittr', 'markdown', 'network', 'NMF', 'pkgconfig', 'png', 'RColorBrewer', 'readxl', 'reshape2', 'rgl', 'rmarkdown', 'scales', 'shinydashboard', 'shinyjs', 'sna', 'statnet.common', 'stats4', 'tcltk', 'testthat', 'tibble'), repos='https://cran.rstudio.com/')"

# Option 1
RUN R -e "install.packages('igraph', repos='https://cran.rstudio.com/')"	

# Option 2
RUN R CMD INSTALL /packages/igraph_1.1.2.tar.gz

EXPOSE 3838

CMD [ "shiny-server" ]
```

**Comment by gaborcsardi** [comment] 2017-10-17 09:48
Can you please tell us the actual error message?

**Comment by smichard** [comment] 2017-10-17 10:01
sure
![error msg](https://user-images.githubusercontent.com/3729382/31658985-efef30c6-b332-11e7-8533-839a42ddec1b.JPG)

**Comment by gaborcsardi** [comment] 2017-10-17 10:03
Duplicate of #213, #220, #226, #230.

**Closed by gaborcsardi** 2017-10-17 10:03 UTC

**Comment by smichard** [comment] 2017-10-20 23:43
thanks for these hints.
Managed to get it working with the following Dockerfile. I found the package `libxml2-devel` to be an important prerequisite

```
FROM centos:7

# Installing Cent OS packages
RUN yum -y update && yum -y install \
	epel-release \
	java-1.8.0-openjdk \
	java-1.8.0-openjdk-devel \
	libapreq2-devel \
	libcurl-devel \
	libpng-devel \
	libtiff-devel \
	libjpeg-turbo-devel \
	libxml2-devel \
	yum-utils && \
	yum clean all

# Installing R
RUN yum -y update && yum -y install \
	R

# Copy Packages	
COPY ./packages /packages

# Installing R-Shiny and R packages
RUN	R -e "install.packages('shiny', repos='http://cran.rstudio.com/')" && \
	yum -y install --nogpgcheck /packages/shiny-server-1.5.3.838-rh5-x86_64.rpm && \
	R -e "install.packages(c('ape', 'broom', 'compiler', 'digest', 'dplyr', 'flexdashboard', 'forcats', 'GGally', 'ggplot2', 'graph', 'igraphdata', 'igraph', 'intergraph', 'irlba', 'maps', 'magrittr', 'markdown', 'network', 'NMF', 'pkgconfig', 'png', 'RColorBrewer', 'readxl', 'reshape2', 'rgl', 'rmarkdown', 'scales', 'shinydashboard', 'shinyjs', 'sna', 'statnet.common', 'stats4', 'tcltk', 'testthat', 'tibble'), repos='https://cran.rstudio.com/')"


EXPOSE 3838

CMD [ "shiny-server" ]
```
