### ISSUE TITLE
Nice to have: consistent treatment of ‘weight’ edge attribute E()$weight.

### ISSUE THREAD

**Issue by clpippel** [igraph/rigraph#1098] opened 2024-01-11 09:48 UTC
**What is the feature or improvement you would like to see?**
Consistent treatment of the ‘weight’ edge attribute E()$weight in igraph functions.

**Use cases for the feature**

Both `cluster_leiden(), cluster_louvain()`  take into account the edge  `$weight` attribute.

- weights 
  The weights of the edges. It must be a positive numeric vector, NULL or NA.
  If it is NULL and the input graph has a ‘weight’ edge attribute,
  then that attribute will be used. If NULL and no such attribute is present,
  then the edges will have equal weights. Set this to NA if the graph was a ‘weight’ edge attribute,
  but you don't want to use it for community detection.
  A larger edge weight means a stronger connection for this function.

In `modularity()` the `$weight` attribute, when present, is ignored.

- weights 	

  If not NULL then a numeric vector giving edge weights.

**Example**s
```
library(igraph)
g <- make_ring(5)
E(g)$weight <- c(2, 2, 1, 3, 3)
E(g)$label  <- E(g)$weight

cle <- cluster_leiden(g, objective_function=c("CPM", "modularity")[2], resolution = 1)
cle$quality                                             # including weights when $weight attribute is present.
modularity(g, membership(cle))                          # ignoring weights, inconsistent with cluster_leiden/louvain().
modularity(g, membership(cle), weights=E(g)$weight )    # for weighted and unweighted graphs.

print.default(cle)
plot(cle, g)
```

**Comment by szhorvat** [comment] 2024-01-11 09:54
Duplicate of #908

**Comment by clpippel** [comment] 2024-01-11 10:17
@szhorvat, Is there an obvious way to produce a list of igraph functions, including parameters?

**Comment by szhorvat** [comment] 2024-01-12 11:22
I'm not sure as R is not my main language. Perhaps someone else can answer.

**Comment by clpippel** [comment] 2024-01-12 14:54
With help of stackoverflow I found:

```
## filter all functions in igraph with parameter "weights".
library(igraph)
fnm <- lsf.str("package:igraph")
res <- 
  cbind(fun=as.list(fnm[seq_along(fnm)]), 
       args=lapply(fnm, \(x) names(formals(get(x, .GlobalEnv)))),
       param=sapply(fnm, \(x) deparse(args(get(x, .GlobalEnv)))[[1]])) |>
  data.frame(row.names=NULL)
res[which(grepl("weights",  res$args)), ] [,1:2]    
```

**Comment by maelle** [comment] 2024-02-26 15:40
Closing as this is a duplicate, as noted above by @szhorvat

**Closed by maelle** 2024-02-26 15:40 UTC
