### ISSUE TITLE
"polygon()" error when setting "edge.width" to a vector in R-3.6.3

### ISSUE THREAD

**Issue by MingwuDuan** [igraph/rigraph#436] opened 2020-12-16 13:03 UTC
**Describe the bug**
When setting "edge.width" to a vector, the terminal shows the error message:
`Error in polygon(p[1, ], p[2, ], border = color, lwd = width, lty = lty) : `
`invalid value specified for graphical parameter "lwd"`

**To reproduce**
library(igraph)
data <- matrix(sample(0:1, 100, replace=TRUE, prob=c(0.8,0.2)), nc=10)
network <- graph_from_adjacency_matrix(data, mode='undirected', diag=T)
plot(network, edge.width=seq(1,10))

**Version information**
Version 1.2.6 from CRAN in R-3.6.3(Win7, x64)

**Comment by hua1991** [comment] 2021-10-05 17:34
@MingwuDuan Hello, have you find ways to resolve this problem? I also encountered this error, but with no idea how to fix it.
Thanks.

**Comment by ntamas** [comment] 2021-10-06 08:27
This is caused by a bug in the graph plotter; it happens for loop edges when the edge width vector is shorter than the number of edges. Either make sure that the edge width vector contains at least as many elements as the number of edges, or remove the loop edges from your graph before plotting.

**Comment by mbojan** [comment] 2021-10-06 08:46
I can indeed reproduce it:

``` r
library(igraph)
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union
set.seed(666) # added for reproducibility
data <- matrix(sample(0:1, 100, replace=TRUE, prob=c(0.8,0.2)), nc=10)
network <- graph_from_adjacency_matrix(data, mode='undirected', diag=T)
try(
  plot(network, edge.width=seq(1, 10))
)
```


    #> Error in polygon(p[1, ], p[2, ], border = color, lwd = width, lty = lty) : 
    #>   invalid value specified for graphical parameter "lwd"

Do note that in the above the `edge.width` argument is getting recycled
because the number of edges is

``` r
ecount(network)
#> [1] 21
```

instead of 10. This works:

``` r
plot(network, edge.width=seq(1, ecount(network)))
```



I believe the problem is with recycling `edge.width` when there are loops.
The code identifies which edges are loops and then tries the access the
corresponding values of `edge.width`. If it is too short, then there is an
error:

``` r
which(is.loop(network)) # which edge is a loop?
#> [1] 12
```

Error because `edge.width` is too short:

``` r
try(
  plot(network, edge.width=seq(1, 10))
)
```



    #> Error in polygon(p[1, ], p[2, ], border = color, lwd = width, lty = lty) : 
    #>   invalid value specified for graphical parameter "lwd"

No error because `edge.width` has a value on 12
position and is recycled otherwise:

``` r
plot(network, edge.width=seq(1, 12))
```



I guess the function should properly recycle the arguments, even if there are
loops.

<sup>Created on 2021-10-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ntamas** [comment] 2021-10-06 08:57
I'm not sure whether recycling is the way to go here; on one hand I understand that recycling is a common thing in the R world, but on the other hand we would be breaking backward compatibility if we suddenly added recycling to the `edge.width` argument. The current behaviour is _not_ to recycle, and edges without a specified width in the `edge.width` vector will not be plotted at all. To add insult to injury, the documentation states that "shorter vectors are recycled" (see [here](https://igraph.org/r/html/1.2.6/plot.common.html) ), which holds only if `edge.width` is a single number.

All in all, I'm leaning towards fixing this in the future and start recycling vectors properly, but most likely there will only be a quick fix for the original issue reported here in 1.2.7 due to lack of time. We can then sort this out properly for 1.3.

**Comment by mbojan** [comment] 2021-10-06 09:08
Ha! You are correct about not to recycle. I haven't noticed that earlier. I guess in this particular context it perhaps does not make sense to recycle vectors longer than 1. A more informative error message would be nice.

**Comment by nickharrigan** [comment] 2022-02-22 04:48
I'm still getting this error, FYI

`Error in polygon(p[1, ], p[2, ], border = color, lwd = width, lty = lty) : 
invalid value specified for graphical parameter "lwd"`

**Comment by ntamas** [comment] 2022-02-22 14:46
Thanks, it looks like I was sloppy and forgot to check whether `plot.bezier()` is happy with a zero line width (which is used in place of NA now). Changed the fallback to 1.

**Comment by ntamas** [comment] 2022-03-25 16:24
Seems to work with a fallback line width of 1 so closing. Feel free to reopen if needed.

**Closed by ntamas** 2022-03-25 16:24 UTC
