### ISSUE TITLE
rigraph fails to compile

### ISSUE THREAD

**Issue by fbreitwieser** [igraph/rigraph#155] opened 2016-05-27 20:50 UTC
Hi,
I'm trying to install the igraph R package on a server, but it fails with the following message when compiling AMD / CHOLMOD:

The setup:
R 3.2
GNU Fortran (GCC) 4.8.5
Linux igm3 2.6.18-348.1.1.el5 #1 SMP Tue Jan 22 16:26:03 EST 2013 x86_64 x86_64 x86_64 GNU/Linux
AMD Opteron(tm) Processor 6172

```
> devtools::install_github("igraph/rigraph")
Downloading GitHub repo igraph/rigraph@master
from URL https://api.github.com/repos/igraph/rigraph/zipball/master
Installing igraph
'/data1/igm3/sw/packages/R_install/R-3-2/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD
INSTALL  \
  '/tmp/RtmpXEySvV/devtools3c91642da9d4/igraph-rigraph-057cc9d' --library='/home/fbreitwieser/R/x86_64-pc-linux-gnu-lib
rary/3.2' --install-tests

* installing *source* package 'igraph' ...
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...

...

checking for __gmpz_add in -lgmp... no
configure: creating ./config.status
config.status: creating src/Makevars.tmp
config.status: creating src/Makevars
config.status: creating src/config.h
** libs
gfortran   -fpic  -g -O2  -c AMD/Source/amd.f -o AMD/Source/amd.o
gcc -std=gnu99 -I/data1/igm3/sw/packages/R_install/R-3-2/lib64/R/include -DNDEBUG  -I/data1/igm3/sw/include   -DUSING_R
 -I. -Iinclude -Ics -Iglpk -Iplfit -ICHOLMOD/Include -IAMD/Include -ICOLAMD/Include -ISuiteSparse_config -I/data1/igm3/
sw/include -g -O2 -msse2 -I/data1/igm3/sw/include -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1
.1.0\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fpic  -g -O2 -msse2 -I/data1/igm3/sw/include  -c AMD/Source/amd_1.
c -o AMD/Source/amd_1.o

...

gfortran   -fpic  -g -O2  -c AMD/Source/amdbar.f -o AMD/Source/amdbar.o
gcc -std=gnu99 -I/data1/igm3/sw/packages/R_install/R-3-2/lib64/R/include -DNDEBUG  -I/data1/igm3/sw/include   -DUSING_R
 -I. -Iinclude -Ics -Iglpk -Iplfit -ICHOLMOD/Include -IAMD/Include -ICOLAMD/Include -ISuiteSparse_config -I/data1/igm3/
sw/include -g -O2 -msse2 -I/data1/igm3/sw/include -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1
.1.0\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fpic  -g -O2 -msse2 -I/data1/igm3/sw/include  -c CHOLMOD/Check/cho
lmod_check.c -o CHOLMOD/Check/cholmod_check.o
CHOLMOD/Check/cholmod_check.c: In function 'cholmod_gpu_stats':
CHOLMOD/Check/cholmod_check.c:621:50: error: 'cholmod_common' has no member named 'CHOLMOD_CPU_SYRK_CALLS'
     P2 ("SYRK  CPU calls %12.0f", (double) Common->CHOLMOD_CPU_SYRK_CALLS) ;
                                                  ^
CHOLMOD/Check/cholmod_check.c:86:36: note: in definition of macro 'PR'
  (Common->print_function) (format, arg) ; \
                                    ^
CHOLMOD/Check/cholmod_check.c:621:5: note: in expansion of macro 'P2'
     P2 ("SYRK  CPU calls %12.0f", (double) Common->CHOLMOD_CPU_SYRK_CALLS) ;
     ^
CHOLMOD/Check/cholmod_check.c:622:33: error: 'cholmod_common' has no member named 'CHOLMOD_CPU_SYRK_TIME'
     P2 (" time %12.4e\n", Common->CHOLMOD_CPU_SYRK_TIME) ;
                                 ^
CHOLMOD/Check/cholmod_check.c:86:36: note: in definition of macro 'PR'
  (Common->print_function) (format, arg) ; \
                                    ^
CHOLMOD/Check/cholmod_check.c:622:5: note: in expansion of macro 'P2'
     P2 (" time %12.4e\n", Common->CHOLMOD_CPU_SYRK_TIME) ;
     ^
CHOLMOD/Check/cholmod_check.c:623:50: error: 'cholmod_common' has no member named 'CHOLMOD_GPU_SYRK_CALLS'
     P2 ("      GPU calls %12.0f", (double) Common->CHOLMOD_GPU_SYRK_CALLS) ;
                                                  ^
CHOLMOD/Check/cholmod_check.c:86:36: note: in definition of macro 'PR'
  (Common->print_function) (format, arg) ; \

...

CHOLMOD/Check/cholmod_check.c:86:36: note: in definition of macro 'PR'
  (Common->print_function) (format, arg) ; \
                                    ^
CHOLMOD/Check/cholmod_check.c:649:5: note: in expansion of macro 'P2'
     P2 ("  %12.4e\n", Common->CHOLMOD_ASSEMBLE_TIME2) ;
     ^
/data1/igm3/sw/packages/R_install/R-3-2/lib64/R/etc/Makeconf:134: recipe for target 'CHOLMOD/Check/cholmod_check.o' failed
make: *** [CHOLMOD/Check/cholmod_check.o] Error 1
ERROR: compilation failed for package 'igraph'
* removing '/home/fbreitwieser/R/x86_64-pc-linux-gnu-library/3.2/igraph'
Error: Command failed (1)
```

**Comment by gdreiman1** [comment] 2016-08-10 21:35
@fbreitwieser did you ever resolve this?

**Comment by ntamas** [comment] 2022-01-02 21:20
Closing as the issue is not relevant any more; newer versions of igraph don't include `CHOLMOD` any more.

**Closed by ntamas** 2022-01-02 21:20 UTC
