### ISSUE TITLE
install of igraph 1.6.0 fails under R 4.3.1 on CentOS

### ISSUE THREAD

**Issue by Ganson2018** [igraph/rigraph#1194] opened 2024-02-04 10:25 UTC
What happens?
When try to compile/install igraph 1.6.0 under R 4.3.1 on CentOS Linux 7, I receive a compile error
I had installed glpk-devel gmp-devel libxml2-devel
conda version : 23.7.4

```
install.packages("igraph")

* installing *source* package ‘igraph’ ...
** using staged installation
libxml2 include directory: /mypath/Tools/miniconda3/envs/R4.3/include/libxml2 -I/mypath/Tools/miniconda3/envs/R4.3/include
** libs
using C compiler: ‘x86_64-conda-linux-gnu-cc (conda-forge gcc 13.1.0-0) 13.1.0’
using C++ compiler: ‘x86_64-conda-linux-gnu-c++ (conda-forge gcc 13.1.0-0) 13.1.0’
x86_64-conda-linux-gnu-cc -I"/mypath/Tools/miniconda3/envs/R4.3/lib/R/include" -DNDEBUG -DUSING_R -I. -Ivendor -Ivendor/cigraph/src -Ivendor/cigraph/include -Ivendor/cigraph/vendor -I"/mypath/Tools/miniconda3/envs/R4.3/include/libxml2 -I/mypath/Tools/miniconda3/envs/R4.3/include" -DNDEBUG -DNTIMER -DNPRINT -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL= -DPRPACK_IGRAPH_SUPPORT -DHAVE_GFORTRAN=1 -D_GNU_SOURCE=1 -I'/mypath/Tools/miniconda3/envs/R4.3/lib/R/library/cpp11/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /mypath/Tools/miniconda3/envs/R4.3/include -I/mypath/Tools/miniconda3/envs/R4.3/include -Wl,-rpath-link,/mypath/Tools/miniconda3/envs/R4.3/lib   -fvisibility=hidden -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /mypath/Tools/miniconda3/envs/R4.3/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1689933267587/work=/usr/local/src/conda/r-base-4.3.1 -fdebug-prefix-map=/mypath/Tools/miniconda3/envs/R4.3=/usr/local/src/conda-prefix  -c vendor/cigraph/src/io/graphml.c -o vendor/cigraph/src/io/graphml.o
vendor/cigraph/src/io/graphml.c:46:10: fatal error: libxml/globals.h: No such file or directory
   46 | #include <libxml/globals.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/mypath/Tools/miniconda3/envs/R4.3/lib/R/etc/Makeconf:193: vendor/cigraph/src/io/graphml.o] Error 1
ERROR: compilation failed for package ‘igraph’
```
If you need any additional information, please let me know.

**Comment by szhorvat** [comment] 2024-02-04 10:41
Duplicate of #1181

**Closed by szhorvat** 2024-02-04 10:41 UTC
