### ISSUE TITLE
Incomprehensible error message: Error in if (axes) { : the condition has length > 1

### ISSUE THREAD

**Issue by clpippel** [igraph/rigraph#790] opened 2023-04-22 10:16 UTC
**Describe the bug**
Consider the following code.

**To reproduce**
```
library(igraph)
igraph_version()
## [1] "1.4.2"
r4 <- make_ring(4)
lyt <- layout_on_grid(r4)
lyt[4,2]
## [1] 1
lyt[4,2] <- 1
plot(r4, lyt)
## Error in if (axes) { : the condition has length > 1
```
**Version information**

 - R/igraph version: ...
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by szhorvat** [comment] 2023-04-22 12:09
Without commenting on how to improve the message, I'll just point out the cause.

----

The second argument of `plot.igraph` is not `layout` but `axes`, which should be a truth value. In the internal implementation, it is used directly in a conditional expression, i.e. the code looks like `if (axes) { ... }`. Since R 4.2.0, it is an error to use a non-scalar value within an `if`.

Simpler ways to show the same:

```
> plot(make_ring(3), axes=c(T,F))
Error in if (axes) { : the condition has length > 1
```

```
> if (c(T,F)) {}
Error in if (c(T, F)) { : the condition has length > 1
```

Other ways to get similarly confusing errors is to pass in values that cannot be coerced into a logical:

```
> plot(make_ring(3), 'x')
Error in if (axes) { : argument is not interpretable as logical
```

**Comment by clpippel** [comment] 2023-04-22 12:46
Thanks for pointing this out. Its a bug in my code. It should be:
`plot(r4, layout = lyt)`

**Comment by ntamas** [comment] 2023-04-23 20:28
In general I think you are likely to find tons of issues like this in igraph's code (or pretty much any R package) if you look hard enough. R does not do type checking so it's easy to post the wrong type of parameters to a function. Adding type checks everywhere is possible, but it is lots of work for little gain and it probably even gives you a performance penalty. So I'm inclined to close this issue now, but feel free to reopen if you disagree.

**Closed by ntamas** 2023-04-23 20:28 UTC
