### ISSUE TITLE
installing Version 1.2.8 from CRAN fails

### ISSUE THREAD

**Issue by pfuehrlich-pik** [igraph/rigraph#489] opened 2021-11-09 10:44 UTC
I get the following error when installing igraph 1.2.8 from CRAN:
```
gcc -I"/p/system/packages/R/3.6.3/lib64/R/include" -DNDEBUG   -I/usr/local/include -DUSING_R -I. -Iinclude -Ics -Iplfit -ISuiteSparse_config -fopenmp -O3 -march=native -mtune=native -I/usr/include/libxml2 -fopenmp -O3 -march=native -mtune=native -I/usr/include/libxml2 -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.2.8\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fpic  -fopenmp -O3 -march=native -mtune=native -c blas.c -o blas.o
In file included from blas.c:26:
blas.c: In function 'igraph_blas_dgemv':
igraph_blas_internal.h:42:29: error: too few arguments to function 'dgemv_'
   42 |     #define igraphdgemv_    dgemv_
      |                             ^~~~~~
blas.c:70:5: note: in expansion of macro 'igraphdgemv_'
   70 |     igraphdgemv_(&trans, &m, &n, &alpha, VECTOR(a->data), &m,
      |     ^~~~~~~~~~~~
igraph_blas_internal.h:42:29: note: declared here
   42 |     #define igraphdgemv_    dgemv_
      |                             ^~~~~~
igraph_blas_internal.h:60:6: note: in expansion of macro 'igraphdgemv_'
   60 | void igraphdgemv_(char *trans, int *m, int *n, igraph_real_t *alpha,
      |      ^~~~~~~~~~~~
blas.c: In function 'igraph_blas_dgemv_array':
igraph_blas_internal.h:42:29: error: too few arguments to function 'dgemv_'
   42 |     #define igraphdgemv_    dgemv_
      |                             ^~~~~~
blas.c:111:5: note: in expansion of macro 'igraphdgemv_'
  111 |     igraphdgemv_(&trans, &m, &n, &alpha, VECTOR(a->data), &m,
      |     ^~~~~~~~~~~~
igraph_blas_internal.h:42:29: note: declared here
   42 |     #define igraphdgemv_    dgemv_
      |                             ^~~~~~
igraph_blas_internal.h:60:6: note: in expansion of macro 'igraphdgemv_'
   60 | void igraphdgemv_(char *trans, int *m, int *n, igraph_real_t *alpha,
      |      ^~~~~~~~~~~~
/p/system/packages/R/3.6.3/lib64/R/etc/Makeconf:168: recipe for target 'blas.o' failed
make: *** [blas.o] Error 1
ERROR: compilation failed for package 'igraph'
Error: install of package 'igraph' failed [error code 1]
```
I believe this could be cause by `0006-fix-lto-warnings.patch`, there is a check for HAVE_GFORTRAN in `blas.c`:
https://github.com/igraph/rigraph/blob/6911ad52d7bdaf0887cfbda71ac7bd75da54f90f/patches/0006-fix-lto-warnings.patch#L155
and
https://github.com/igraph/rigraph/blob/6911ad52d7bdaf0887cfbda71ac7bd75da54f90f/patches/0006-fix-lto-warnings.patch#L169
but not in the corresponding declaration in `igraph_blas_internal.h`:
https://github.com/igraph/rigraph/blob/6911ad52d7bdaf0887cfbda71ac7bd75da54f90f/patches/0006-fix-lto-warnings.patch#L81
So I believe on my system there's a mismatch between declaration and definition. Maybe the HAVE_GFORTRAN check should be patched into `igraph_blas_internal.h` too?
Thanks for looking into this!

**Comment by ntamas** [comment] 2021-11-09 14:55
Try installing `gfortran` first before trying to compile and install igraph from source - I believe this should do the trick. Alternatively, wait a few days until CRAN publishes the binaries for igraph; right now the source is already at 1.2.8 while the binaries are 1.2.7 so R probably opts for compiling from source.

The root cause is already fixed in the C core of igraph (see [here](https://github.com/igraph/igraph/blob/master/src/linalg/blas_internal.h#L60)) but the R interface is still a bit behind the C core; we aim to upgrade the R interface to C-igraph 0.9.x in the near future and then this problem will be gone even if you compile from source without `gfortran`.

**Comment by see24** [comment] 2021-11-09 16:32
I also get an error installing igraph 1.2.8 from CRAN:

```
"C:/rtools40/mingw32/bin/"gcc  -I"C:/R/include" -DNDEBUG -I/mingw32/include/libxml2 -I/mingw32/include -DLIBXML_STATIC -DUSING_R -DHAVE_FMEMOPEN=0 -DHAVE_OPEN_MEMSTREAM=0 -DHAVE_RINTF -DWin32 -DHAVE_LIBXML -DHAVE_UNISTD_H -Wall -DPACKAGE_VERSION=\"1.2.8\" -DHAVE_FMIN=1 -DHAVE_LOG2=1 -DHAVE_SNPRINTF -Ics -I/mingw32/include -DHAVE_GLPK=1 -Iplfit -Iprpack -DIGRAPH_THREAD_LOCAL= -DPRPACK_IGRAPH_SUPPORT -I. -Iinclude -ISuiteSparse_config -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -I/mingw32/include -DINTERNAL_SUITESPARSE      -DINTERNAL_ARPACK -I. -I/mingw32/include -DHAVE_GFORTRAN   -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c feedback_arc_set.c -o feedback_arc_set.o
In file included from feedback_arc_set.c:31:
igraph_glpk_support.h:36:10: fatal error: glpk.h: No such file or directory
 #include <glpk.h>
          ^~~~~~~~
compilation terminated.
make: *** [C:/R/etc/i386/Makeconf:238: feedback_arc_set.o] Error 1
ERROR: compilation failed for package 'igraph'
```

**Comment by ntamas** [comment] 2021-11-09 16:34
GLPK is needed for igraph so install GLPK first, or wait until CRAN publishes the binaries for version 1.2.8. I'm not using Windows so I cannot tell you how to install GLPK there, but maybe @vtraag can chime in.

**Comment by szhorvat** [comment] 2021-11-09 16:49
Regarding compilation failure because GLPK is missing, especially on Windows:

A new complaint comes in about this literally every time a new igraph version is released. The simple answer is: if you are not sure how to resolve compilation issues, just don't compile igraph from source. Install the binary version. R will ask whether you want to compile from source—simply say "no":

```
> install.packages('igraph')

  There is a binary version available but the source
  version is later:
       binary source needs_compilation
igraph  1.2.7  1.2.8              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) no
```

It usually takes a few days until binaries become available—then you will be able to install 1.2.8.

**Comment by szhorvat** [comment] 2021-11-09 16:50
We should really have a FAQ item about this. Also, do we want to redirect support requests to the forum, as we did with the other interfaces, @ntamas? (I.e., create issue templates.) Not sure if @gaborcsardi prefers that.

**Comment by see24** [comment] 2021-11-09 17:02
@ntamas and @szhorvat Thanks yes I can install from the binary. An FAQ would be great since folks like me don't know what GPLK is so wouldn't know that the error is a consequence of not having something installed.

**Comment by ntamas** [comment] 2021-11-09 18:27
@szhorvat I have created issue templates now. We should find a place for the FAQ; alternatively, I can put up a pinned issue on top of the issue list that explains what to do when the new source is already on CRAN but the binaries aren't.

**Comment by vtraag** [comment] 2021-11-09 19:13
Perhaps we should have a separate template for installation problems? Or make clear in the bug report template that they can better go to the discussion forum for installation related problems? The pinned issue also sounds like a good plan, so perhaps we should just do that and see how it goes next time around.

**Comment by szhorvat** [comment] 2021-11-09 19:26
I vote for the pinned issue. For completeness, it should also contain information about how to install GLPK with Rtools on Windows, and what is needed for compilation on Linux (where there are no binaries).

**Closed** 2021-12-29 14:46 UTC
