### ISSUE TITLE
Applying edge betweenness to list of adjacency matrices: R session aborted

### ISSUE THREAD

**Issue by leifeld** [igraph/rigraph#336] opened 2019-04-11 13:07 UTC
I have installed the `igraph` package, version 1.2.4, in R. I have a list of weighted adjacency matrices for which I try to compute edge betweenness communities. At some point in the loop, around the 80th to 90th item in the list, R is aborted. The exact index at which this happens varies between attempts.

I assume there must be some problem with the C implementation, but I don't know what is happening. Some of the networks are trivial, with only three vertices and two weighted edges, but I have no way of knowing that a priori, so it would be good if the R session wasn't just aborted. The problem does not happen with the other community detection measures in the package.

I have compiled a [minimal example](https://github.com/igraph/rigraph/files/3068684/example.zip) and would be grateful if you could take a look and fix the problem. Thanks!

Here is a copy of the R code I use:

``` r
library("igraph")

networks <- readRDS("networks.RDS")

test <- function(x) {
  g <- graph.adjacency(x, mode = "undirected", weighted = TRUE)
  cluster_edge_betweenness(g, directed = FALSE)
}

for (i in 1:length(networks)) {
  print(i)
  test(networks[[i]])
}
```
(The `networks.RDS` file is included in the [example](https://github.com/igraph/rigraph/files/3068684/example.zip).)

**Comment by mbojan** [comment] 2019-04-11 13:21
@leifeld , out of curiosity, are also getting the warnings:

```
> test(networks[[1]])
IGRAPH clustering edge betweenness, groups: 5, mod: 0.42
+ groups:
  $`1`
  [1] "California Institute of Technology - SCI"    
  [2] "Charles River Associates - BUS"              
  [3] "East Harris County Manufacturers - BUS"      
  [4] "Heritage Foundation - NGO"                   
  [5] "Office of Representative Fred Upton - CON-R" 
  [6] "Texas Agriculture - SCI"                     
  [7] "Texas Attorney General Greg Abbot - SUBGOV-R"
  [8] "Texas Public Policy Foundation - NGO"        
  
  + ... omitted several groups/vertices
Warning messages:
1: In cluster_edge_betweenness(g, directed = FALSE, ...) :
  At community.c:460 :Membership vector will be selected based on the lowest modularity score.
2: In cluster_edge_betweenness(g, directed = FALSE, ...) :
  At community.c:467 :Modularity calculation with weighted edge betweenness community detection might not make sense -- modularity treats edge weights as similarities while edge betwenness treats them as distances
```

Perhaps if these are thrown at each and every of the `length(networks)`=1754 iterations something gets overflowed...

**Comment by leifeld** [comment] 2019-04-11 13:28
Yes, but I don't think this can be the problem. If I replace `weighted = TRUE` by `weighted = NULL`, the warnings disappear, but the problem persists.

**Comment by mbojan** [comment] 2019-04-11 13:42
When I run it with `Rscript` I'm getting

```
(...)
[1] 91
[1] 92
free(): invalid pointer
Aborted (core dumped)
```
which suggests that indeed it is something in C I believe. 

I did not run into this myself before even though I do use `cluster_edge_betweenness()` in teaching materials. Would be great to sort it out... @gaborcsardi @ntamas ?

**Comment by ntamas** [comment] 2019-04-15 07:49
Looks like the crash is not deterministic; this is what I got with `Rscript`:

```
(...)
[1] 1209
[1] 1210
[1] 1211
[1] 1212
[1] 1213

 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: i_set_vertex_attr(graph = graph, name = name, index = index,     value = value)
 2: set_vertex_attr(res, add.colnames, value = colnames(adjmatrix))
 3: graph.adjacency(x, mode = "undirected", weighted = TRUE)
 4: test(networks[[i]])
An irrecoverable exception occurred. R is aborting now ...
zsh: segmentation fault  Rscript example.R
```

Later on, I've got this with another attempt:

```
(...)
[1] 117
[1] 118
[1] 119
[1] 120

 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: edge_attr(graph, name, x)
 2: `$.igraph.es`(E(graph), weight)
 3: E(graph)$weight
 4: cluster_edge_betweenness(g, directed = FALSE)
 5: test(networks[[i]])
An irrecoverable exception occurred. R is aborting now ...
zsh: segmentation fault  Rscript example.R
```

Sometimes it runs without errors for the first 1500 networks or so.

If I were to bet, I would say that the error is most likely in the attribute handler in the glue code between the C core and the R layer. I'm not that familiar with the internals of the R interface so I cannot debug it further -- hopefully @gaborcsardi can.

**Comment by leifeld** [comment] 2019-04-15 14:05
Thanks for looking into this. I really appreciate it.

**Comment by nograpes** [comment] 2020-01-22 02:33
I think that this bug _is_ deterministic: it always fails on the 92nd element of the example. This code will always segfault for me on Windows and Linux:

```
# Warning! will segfault and kill your session.
library(igraph)
networks <- readRDS("networks.RDS")
g <- graph.adjacency(networks[[92]], mode = "undirected", weighted = TRUE)
cluster_edge_betweenness(g, directed = FALSE)
# Segfault
```

It turns out that the 92nd element of `networks` has no edges, which I think is the key problem. You can make a much simpler, reproducible version of this bug with:

```
# Warning! will segfault and kill your session.
library(igraph)
g <- make_full_graph(1)
cluster_edge_betweenness(g)
# Segfault
```

**Comment by ntamas** [comment] 2020-01-22 08:28
It does not crash on macOS with igraph 1.2.4.2 and R 3.6.1:

```
> cluster_edge_betweenness(g)
IGRAPH clustering edge betweenness, groups: 1, mod: 0
+ groups:
  $`1`
  [1] 1

> packageVersion("igraph")
[1] ‘1.2.4.2’
```

Can you post your R and igraph version numbers?

**Comment by nograpes** [comment] 2020-01-31 16:08
I have igraph 1.2.4.2, R 3.6.2, and Ubuntu Linux 18.04. 
I have also reproduced the issue on igraph 1.2.4.2, R 3.6.1, and Windows 10.

**Comment by ntamas** [comment] 2020-01-31 20:43
The fix is now merged into the C core.

**Closed** 2022-01-10 19:38 UTC
