### ISSUE TITLE
(potential bug) simple_es_index(x, ii)

### ISSUE THREAD

**Issue by wenskyhe** [igraph/rigraph#874] opened 2023-07-14 07:03 UTC
**Describe the bug**
Error in unclass(x)[i] : only 0's may be mixed with negative subscripts

6.  simple_es_index(x, ii)
5.  FUN(X[[i]], ...)
4. apply(res, function(ii) { if (is.null(ii)) { return(NULL) } ...
3.  `[.igraph.es`(sorted_edges, 1:num_edges_to_delete)
2. sorted_edges[1:num_edges_to_delete]
1.degreeHandleing(Dist12, g1, g2)

</div>
This is triggered when I do the following:

**To reproduce**
 I am not gonna put all the code here b/c it's really long
 in short, g1 and g2 are two graphs and Dist is their distance matrix
 after some handling the g12 is a new graph with corresponding weights assigned. 
```
degreeHandleing <- function(Dist, g1, g2){
  temp <- edgeExchange(Dist, g1, g2)
  p1_edges = temp$p1_edges; p2_edges = temp$p2_edges
  interEC = temp$interEC
  print(p1_edges);print(p2_edges)
  print(interEC)
  g12<- graph(edges = c(p1_edges, p2_edges, interEC), directed = F)
  E(g12)$weight <- c(temp$p1_edges_wei, temp$p2_edges_wei, temp$interEC_wei)
  d=ceiling(vcount(g1)/vcount(g2))
  degrees <- degree(g12)
  while (any(degrees > d)) { 
    nodes_to_adjust <- which(degrees > d)
    for (node in nodes_to_adjust){
      deg <- degrees[node]
      incident_edges <- incident(g12, node)
      incident_edge_weights <- E(g12)$weight[incident_edges]
      sorted_edges <- incident_edges[order(incident_edge_weights)]
      # print(sorted_edges)
      num_edges_to_delete <- deg - d
      edges_to_delete <- sorted_edges[1:num_edges_to_delete]
      # print(edges_to_delete)
      # Delete the edges from the graph
      g12 <- delete.edges(g12, edges_to_delete)
      
      # Update the degrees after edge deletion
      print(g12)
      degrees <- degree(g12)
    }
  }
  return(g12)
}
trail1 <- degreeHandleing(Dist12, g1, g2)

```

**Version information**

 - R/igraph version: "R version 4.2.1 (2022-06-23)"
 - R version: ‘1.5.0’
 - Operating system:  sysname "Darwin"

**Comment by clpippel** [comment] 2023-07-15 10:09
Your code is not reproducible. The function _edgeExchange()_ is not defined.

**Comment by maelle** [comment] 2024-03-05 07:52
Closing, @wenskyhe please open a new issue with a reproducible example if the problem persists.

**Closed by maelle** 2024-03-05 07:52 UTC

**Comment by clpippel** [comment] 2024-03-05 13:51
This is not a bug but an error in de code.

Change ` edges_to_delete <- sorted_edges[1:num_edges_to_delete]`
  into
`edges_to_delete <- sorted_edges[seq_len(num_edges_to_delete)]`

This will work if edges_to_delete is empty and 1:0 is nonempty.

**Comment by maelle** [comment] 2024-03-07 10:26
thanks so much @clpippel
