### ISSUE TITLE
cluster_walktrap issue non-negative vector

### ISSUE THREAD

**Issue by steve-real** [igraph/rigraph#540] opened 2022-06-14 16:44 UTC
SUCom <- cluster_walktrap(SuGraph,steps=4)

I ran this line of code for some time know with no issues. I still am able to run it perfectly on one PC, however, on another I keep getting the following error:

Error in cluster_walktrap(SuGraph, steps = 4) : 
  At core/community/walktrap/walktrap.cpp:149 : Weight vector must be non-negative. Invalid value

Any ideas?

**Comment by ntamas** [comment] 2022-06-14 16:46
Are the two computers running the same version of igraph? We have recently added a check to the internal C code of the walktrap community detection algorithm that validates whether all weights are non-negative. Is your graph weighted? If so, what's the minimum weight in the graph?

**Comment by steve-real** [comment] 2022-06-14 16:55
Mmh yeah. The first computer (the one where the command works) runs version 1.2.6. The other one runs the newer 1.3.1. In the context of what you told me (the added check), it now makes sense. My graph is weighted, the minimum weight being -0.22311.

Any solution to this? Thank you for your quick response btw.

**Comment by ntamas** [comment] 2022-06-14 17:00
Well, the walktrap algorithm never made sense with negative weights - it is based on random walks where each edge is traversed with a probability proportional to the weight of that edge, so how would you handle negative probabilities? :) Whatever results you obtained with 1.2.6 probably did not make sense for that particular edge and its vicinity.

If your weights represent similarities and negative weights represent dissimilarity, the easiest is just to drop the edges with negative weights -- the absence of an edge should be enough indication for walktrap to consider two nodes as dissimilar.

**Comment by ntamas** [comment] 2022-06-14 17:01
Closing the issue as it's not a bug.

**Closed by ntamas** 2022-06-14 17:01 UTC
