### ISSUE TITLE
Wishlist: R interface to feedback_arc_set.c functions

### ISSUE THREAD

**Issue by gaiazaff** [igraph/rigraph#218] opened 2017-08-06 13:48 UTC
It would be good to be able to solve feedback arc set problems in R.

**Comment by bachi55** [comment] 2017-08-06 17:45
Some time ago I made necessary modifications in my local copy of 'rigraph'. I was just about to open an issue in order to finally bring those modifications to the repository.

I will submit a pull request for as in the coming week.

**Comment by ben519** [comment] 2018-10-22 17:46
+1 For this

**Comment by szhorvat** [comment] 2022-03-11 18:06
Before we close this @ntamas, I am wondering if it would make sense to have `approx` as the default method.

I know why you would choose `exact` as the default. I did as well for the Mathematica interface. But now I'm of the opinion that `approx` is a better choice.

 - The function name is `feedback_arc_set`, not `minimum_feedback_arc_set`, so using `approx` as the default would not make the naming inaccurate
 - The exact method is _extremely_ slow. Except for the tiniest graphs, it never finishes and needs to be interrupted.
 - We only added GLPK interruption support relatively recently and there are still problems when compiling with MinGW. See the occasional CI test failures in the C core repo (it crashes). I could never debug this and I suspect that it's not a bug in igraph, but a problem with MinGW's longjmp implementation.
 - We're still not sure if we can provide GLPK support out of the box. I just compiled the latest dev version and for some reason it didn't pick up my GLPK (again!). I still have to debug it.

BTW I know how to implement a fast exact method, but I don't have the time. Would make a good project for a student ...

**Comment by ntamas** [comment] 2022-03-11 20:32
>  just compiled the latest dev version and for some reason it didn't pick up my GLPK (again!). I still have to debug it.

Check the output of `configure.log` and let me know if you find anything weird/unexpected there. My aim with the current implementation in `configure.ac` was only to make sure that GLPK is picked up correctly on R's win-builder and mac-builder services and on R-hub. Anything else may be hit-and-miss.

I am okay with changing the default to `approx`.

**Closed** 2022-03-13 17:35 UTC
