### ISSUE TITLE
R Interface: graph.strength implementation does not match documentation

### ISSUE THREAD

**Issue by ntamas** [igraph/rigraph#138] opened 2016-01-20 10:54 UTC
_From @se4u on January 19, 2016 23:16_

Hi
I am running igraph version 1 and I found that the graph.strength implementation is at odds with the documentation. The following code illustrated the problem:

    1> igraph.version()
        [1] "1.0.0"
    2> d = graph.strength(g, loops=FALSE)
        Error in .Call("R_igraph_strength", graph, vids - 1, mode, loops, weights,  :
        At structural_properties.c:5937 : Invalid weight vector length, Invalid value
    3> d <- graph.strength(g, vids=V(g), loops=FALSE)

Line 2 gives an error but line 3 passes. The documentation says that if `vids` is not provided then automatically `vids=V(g)` would be used. 

_Copied from original issue: igraph/igraph#913_

**Comment by ntamas** [comment] 2016-01-20 10:58
Works fine for me in R-igraph 1.0.0:

```
> library(igraph)
> igraph.version()
[1] "1.0.0"
> g <- grg.game(100, 0.2)
> E(g)$weight <- 1:1000
Warning message:
In eattrs[[name]][index] <- value :
  number of items to replace is not a multiple of replacement length
> graph.strength(g, loops=F)
  [1]   10   19   50   20   37   73  105   67  102  145   91  180  436  585  492
 [16]  244  858 1139  511 1318 1437  678 1569  705 1071 1254 1023 2421 2155 1123
 [31] 1985 2560 2633 1664 2696 1869 3454 2102 3254 2425 3482 2590 2351 2077 3518
 [46] 2300 3992 3928 2628 2367 3030 2774 3693 3423 4175 3532 5993 3138 3898 5363
 [61] 1941 3973 2837 4831 5853 5263 2978 3552 3578 5811 3886 5916 6073 5685 6130
 [76] 2486 5026 6092 5591 4096 2287 4926 2301 4198 3372 5652 4333 3453 4320 3971
 [91] 4823 2898 1932 1467 2990 2486 3549 2490 3555 2549
```

Also, note that the latest version of igraph on CRAN is 1.0.1.

**Comment by se4u** [comment] 2016-01-20 16:44
Sorry, I reported the issue incorrectly.
The problem occurs when I put in `weights="weight"` as a named parameter. While debugging I got confused as to which option was actually giving the errors. The traceback I posted originally also says that the problem is about the length of the weight vector. 

    > dd <- graph.strength(g, vids=V(g), loops=FALSE, weights="weight")
       > Error in .Call("R_igraph_strength", graph, vids - 1, mode, loops, weights,  :
       At structural_properties.c:5937 : Invalid weight vector length, Invalid value
    > dd <- graph.strength(g, vids=V(g), loops=FALSE)

Thanks again for all your help.

**Comment by ntamas** [comment] 2016-01-20 16:48
AFAIK you cannot put `weight` there (unlike in the Python interface); you need to put `E(g)$weight`.

**Comment by se4u** [comment] 2016-01-20 17:54
Aah, I got it. I was just being dumb and misreading the documentations for `strength`. I got the (wrong) impression from the docs that the `weights` parameters was meant to be the `name` of an `edge_attribute`. Thanks again. I am closing the issue.

    strength(graph, vids = V(graph), mode = c("all", "out", "in", "total"),
      loops = TRUE, weights = NULL)
    weights	: Weight vector. If the graph has a weight edge attribute, then this is used by default.

**Closed** 2016-01-20 21:50 UTC
