### ISSUE TITLE
Error in installing igraph in R 3.4.2

### ISSUE THREAD

**Issue by GianRos** [igraph/rigraph#232] opened 2017-10-17 10:54 UTC
Hi, 
new Github user here.
Recently I had a new computer (Linux Ubuntu 16.04), in which I installed the current version of R, 3.4.2 released on 2017-09-28. Unfortunately, in this version I cannot install the igraph package. Below I pasted the last few lines of the installation.
I tried to install igraph on a cluster with R 3.2.2 and it works as usual. 
Thanks!

> ISuiteSparse_config -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.1.1\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c foreign-gml-parser.c -o foreign-gml-parser.o
In file included from src/foreign-gml-parser.y:59:0:
igraph_hacks_internal.h:42:0: warning: "strdup" redefined
>   define strdup igraph_i_strdup
> ^
> In file included from /usr/include/string.h:630:0,
                 from src/foreign-gml-parser.y:54:
> /usr/include/x86_64-linux-gnu/bits/string2.h:1291:0: note: this is the location of the previous definition
>    define strdup(s) __strdup (s)
> ^
> gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG     -DUSING_R -I. -Iinclude -Ics -Iglpk -Iplfit -ICHOLMOD/Include -IAMD/Include -ICOLAMD/Include -ISuiteSparse_config -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.1.1\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c foreign-graphml.c -o foreign-graphml.o
foreign-graphml.c: In function ‘igraph_write_graph_graphml’:
foreign-graphml.c:1408:46: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "<graphml xmlns=\"" GRAPHML_NAMESPACE_URI "\"\n");
                                              ^
foreign-graphml.c:1412:59: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "         xsi:schemaLocation=\"" GRAPHML_NAMESPACE_URI "\n");
                                                           ^
foreign-graphml.c:1414:38: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "         " GRAPHML_NAMESPACE_URI "/1.0/graphml.xsd\">\n");
                                      ^
> /usr/lib/R/etc/Makeconf:159: recipe for target 'foreign-graphml.o' failed
make: *** [foreign-graphml.o] Error 1
ERROR: compilation failed for package ‘igraph’
>* removing ‘/home/grossi2/R/x86_64-pc-linux-gnu-library/3.4/igraph’
> The downloaded source packages are in
	‘/tmp/Rtmpk2zcui/downloaded_packages’
> Warning message:
> In install.packages("igraph") :
  installation of package ‘igraph’ had non-zero exit status
>

**Comment by gaborcsardi** [comment] 2017-10-17 11:30
Seems like a duplicate of #213, #220, #226, #230, #231.

**Closed by gaborcsardi** 2017-10-17 11:30 UTC
