### ISSUE TITLE
Cannot load igraph library using R kernel in Jupyter NB. 

### ISSUE THREAD

**Issue by drives28** [igraph/rigraph#537] opened 2022-05-26 16:09 UTC
Error Message(s):
Error: package or namespace load failed for 'igraph' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Users/drive/anaconda3/envs/r4-base/lib/R/library/igraph/libs/x64/igraph.dll':
  LoadLibrary failure:  The specified procedure could not be found.

A separate pop-up states "The procedure entry point quadmath_snprint could not be located in the dynamic link library. C:\Users\drive\anaconda3\envs\r4-base\lib\R\library\igraph\libs\x64\igraph.dll"

The igraph.dll file does exist on my system.

How issue started:
I have updated my R environment via conda to R 4.1.3. Other R scripts are performing as expected. Two packages will not open clusterProfiler and enrichPlot. These packages appear to rely on igraph as I get the exact same error message when trying to install both packages. I also get this message if I try to view the library for igraph. My attempts at troubleshooting tell me the issue is with igraph but I have no idea how to fix this for myself. 

Feel free to respond with questions and I will do my best to answer them. 

Thanks!

**Comment by ntamas** [comment] 2022-05-26 16:13
Probably a duplicate of https://github.com/igraph/rigraph/issues/534

Long story short: igraph links to `Rlapack.dll`. In the official versions of R, this DLL includes `quadmath_snprintf` that igraph uses. Apparently, the version in Anaconda R does not include this symbol. How did you install `igraph` in Anaconda R? DId you just type `install.packages("igraph")` and it downloaded a binary package for you, or did you compile it from source?

**Comment by drives28** [comment] 2022-05-26 16:14
I tried install.packages("igraph") followed by library("igraph"). Same result.

**Comment by drives28** [comment] 2022-05-26 16:25
If I just run through R 4.2.0 on my local system (no Jupyter, conda, etc.) I get the following:
> install.packages("igraph")
Installing package into ‘C:/Users/drive/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
also installing the dependencies ‘magrittr’, ‘pkgconfig’

trying URL 'https://mirror.las.iastate.edu/CRAN/bin/windows/contrib/4.2/magrittr_2.0.3.zip'
Content type 'application/zip' length 226343 bytes (221 KB)
downloaded 221 KB

trying URL 'https://mirror.las.iastate.edu/CRAN/bin/windows/contrib/4.2/pkgconfig_2.0.3.zip'
Content type 'application/zip' length 22290 bytes (21 KB)
downloaded 21 KB

trying URL 'https://mirror.las.iastate.edu/CRAN/bin/windows/contrib/4.2/igraph_1.3.1.zip'
Content type 'application/zip' length 5806626 bytes (5.5 MB)
downloaded 5.5 MB

package ‘magrittr’ successfully unpacked and MD5 sums checked
package ‘pkgconfig’ successfully unpacked and MD5 sums checked
package ‘igraph’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\drive\AppData\Local\Temp\RtmpcrMegm\downloaded_packages
> library("igraph")

Attaching package: ‘igraph’

The following objects are masked from ‘package:stats’:

    decompose, spectrum

The following object is masked from ‘package:base’:

    union

**Comment by drives28** [comment] 2022-05-26 16:27
I'm not the savviest at this kind of work, so let me know if I'm missing something.

**Comment by ntamas** [comment] 2022-05-26 17:06
Seems like it works flawlessly with the official R release, and I'm not very familiar with Anaconda R so I'm afraid I cannot help much with that. I vaguely remember that Anaconda R was based on Microsoft R Open (i.e. MRO) and I already know that there were problems with that. Any chance to figure out whether your version of R in Anaconda is based on Microsoft R Open?

Alternatively -- I don't really like saying that, but try taking Rlapack.dll from the official R and replacing Rlapack.dll in Anaconda R with the version from the official R. This is a horrible hack, but if it fixes igraph in Anaconda R, it indicates that Anaconda R is messing around with Rlapack.dll in a way that makes binary packages from the official CRAN repository incompatible with Anaconda R.

**Comment by drives28** [comment] 2022-05-26 17:25
I have no idea how to figure out if it is MRO-based. Found this from an article in 2018. https://www.anaconda.com/blog/introducing-microsoft-r-open-as-default-r-for-anaconda-distribution 
"Because MRO is now the default R for Anaconda, users installing R for the first time into an environment will get MRO conda packages"

Thanks for the hack suggestion. I'll try if I get desperate enough (which might not take long). I just wish I knew how to take R on my local machine and run it through jupyter notebook. Last time I created an R conda env I think I got lucky enough that both were matching versions. Not the case this time. :/

**Comment by drives28** [comment] 2022-05-26 17:56
Just fyi. Replacing the Rlapack.dll file did not fix the issue

**Comment by drives28** [comment] 2022-05-26 18:53
I also tried downgrading the igraph version using the following:

#install.packages("remotes")
#remotes::install_version("igraph", version = "1.2.1")

but alas no fix, same error output. Acknowledge my above code might be wrong but I don't get the error message until I call the library.

**Comment by ntamas** [comment] 2022-05-26 19:29
Can you try uninstalling the `igraph` package that you installed and then installing it from `conda`? I.e., by following the instructions [here](https://github.com/conda-forge/r-igraph-feedstock#installing-r-igraph). This is not maintained by us but it seems like a semi-official way to run `igraph` inside Anaconda's R environment.

**Comment by szhorvat** [comment] 2022-05-26 20:04
First, if all you want is to use R from a Jupyter notebook, you do not need to install R from Anaconda. It works fine with the CRAN R distribution.

----

If you still want to use R from conda, then you should also install igraph from conda, not from CRAN. I suggest you install both R and r-igraph from the conda-forge channel. These versions work fine together on macOS. If they don't work well on Windows, you should report the issue to [conda-forge](https://github.com/conda-forge/r-igraph-feedstock). 

I would _strongly_ suggest _not_ to replace DLLs unless you know what you are doing ...

For support requests, please use [the forum](https://igraph.discourse.group/) in the future. We would like to reserve the issue tracker for bug reports and well-articulated feature requests.

----

So far, it does not look like this is a problem with igraph, so I'm closing the issue. Discussion can continue if necessary.

**Closed by szhorvat** 2022-05-26 20:04 UTC

**Comment by szhorvat** [comment] 2022-05-26 20:09
Note that there are multiple versions of R packages on Anaconda, see [r](https://anaconda.org/r/) and [conda-forge](https://anaconda.org/conda-forge/). Only the ones on conda-forge are well-maintained, so you should install _both_ R itself and r-igraph from there in order to ensure that they are compatible with each other.

But once again, if all you need is using R in a Jupyter notebook, this is not necessary.

**Comment by drives28** [comment] 2022-05-26 22:27
YAY! ok. So this fixed the issue. Thanks for getting me to solution! I'm providing lots of basic notes here for those of us who are novices at this kind of work. 

Essentially I followed these instructions for creating my latest R updated conda environment. Note: use "--name" instead of 
"-name". I tried the latter and it didn't work. It may not matter but maybe it does. idk. 
https://www.pohnson.info/r/adding-latest-r-version-to-jupyter-notebook/ 

Following everyone's advice (thank you again!) I went back into the anaconda prompt and applied the command 
conda activate r4-base 
(I had already closed out of the prompt so if you follow those above instructions and you are already in the r4-base for conda, you should be where you are supposed to be). Then applied instructions provided by @ntamas at the following link: https://github.com/conda-forge/r-igraph-feedstock#installing-r-igraph 
after installing igraph within my r environment within conda, I reopened my jupyter notebook and all packages are installing as intended now. 

As a final question for you all, why is it igraph was not installed when I created my new/updated R conda environment? I've never had to do this before, so I would love an answer. 

Thanks to all for your help. I appreciate it, particularly since there is a language barrier with people who are familiar vs. not. 

YAY!

**Comment by szhorvat** [comment] 2022-05-27 07:41
One final note:

I suppose you had other reasons for using R from Anaconda than wanting to use Jupyter (otherwise CRAN R would work fine). Note that igraph is not compiled with the full feature set in Anaconda, simply due to an oversight. See here: https://github.com/conda-forge/r-igraph-feedstock/issues/29
