### ISSUE TITLE
segfault from as.undirected()

### ISSUE THREAD

**Issue by alubbock** [igraph/rigraph#279] opened 2018-06-01 02:15 UTC
I get a segmentation fault when calling `as.undirected()` on a specific graph ([attached as zipped GML](https://github.com/igraph/rigraph/files/2060745/segfault-graph.gml.zip)). Here's a script to reproduce together with my `sessionInfo`:

```r
> library(igraph)

Attaching package: ‘igraph’

The following objects are masked from ‘package:stats’:

    decompose, spectrum

The following object is masked from ‘package:base’:

    union

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin17.3.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] igraph_1.2.1

loaded via a namespace (and not attached):
[1] compiler_3.4.3  magrittr_1.5    pkgconfig_2.0.1
> g <- read.graph('~/segfault-graph.gml', format='gml')
> as.undirected(g)
Error in sum("-100") : invalid 'type' (character) of argument

 *** caught segfault ***
address 0xa, cause 'memory not mapped'

Traceback:
 1: .Call(C_R_igraph_finalizer)
 2: as.undirected(g)
```

**Comment by szhorvat** [comment] 2022-01-10 18:44
This still crashed in the 1.3 dev version.

**Comment by szhorvat** [comment] 2022-01-10 18:50
A simpler way to trigger the crash is to create a directed graph with reciprocal edges and a string-type `weight` attribute, then convert to undirected. Something must be wrong with the attribute combiner.

```
g=make_graph(c(1,2, 2,1))
E(g)$weight <- c('a','b')
as.undirected(g)
```

**Comment by ntamas** [comment] 2022-01-11 13:18
I think the problem is most likely with the error handling in attribute combination functions all over the place in `rinterface.c.in` (in this particular case, `R_igraph_ac_sum_numeric` or `R_igraph_ac_all_other`). I'll investigate this.

**Comment by ntamas** [comment] 2022-01-11 22:05
Okay, I think I figured this out (took the whole day but it was a good learning experience). I'm writing a summary here for posterity and also because I know that @szhorvat will read this and then he will also know what to be careful about.

So, what happens is as follows:

* calling `as.undirected()` goes all the way down to `igraph_to_undirected()`, which allocates a bunch of internal data structures and puts them on igraph's internal "finally" stack so they can be destroyed with `IGRAPH_FINALLY_FREE()` when needed
* eventually, `igraph_to_undirected()` calls the `combine_edges()` function from the attribute handler, letting the higher level interface (i.e. R) know about the sets of edges that are being merged into a single one
* the call leads to `R_igraph_attribute_combine_edges()`, which eventually calls back to R to run the `sum()` function on the `weight` attribute of the edges being merged.
* `sum()` blows up because you cannot add strings together, and it calls R's `error()` function. `error()` in turn executes a `longjmp()`, restoring the entire call stack to an earlier point. _At this point, any variables that igraph functions allocated on the stack are still available, but they are in a part of the stack that has already been unwound_. (Well, not unwound, because a `longjmp()` does not perform a proper stack unwinding, it just restores the stack pointer to the state that was valid when `setjmp()` was called).
* After the `longjmp()`, R calls `R_igraph_finalizer()`, which in turn resets igraph's internal progress bar to zero (by calling an R function from C and potentially overwriting parts of the now-unwound stack), then calls `IGRAPH_FINALLY_FREE()`. This is a problem because the "finally" stack _could_ (and actually, _does_) contain pointers to variables in the stack that may have potentially been overwritten by whatever R was doing between the return from `longjmp()` and the time it called `IGRAPH_FINALLY_FREE()`.

In this particular case, we have an instance of an `igraph_fixed_vectorlist_t` allocated on the stack, deep within `igraph_to_undirected()`. This instance gets corrupted between the `longjmp()` and the call to `IGRAPH_FINALLY_FREE()`, which then results in a crash.

**Comment by szhorvat** [comment] 2022-01-12 07:25
I read it, but I still don't know what to be careful about. R's eager use of `longjmp()` is nasty. What can we do about this? Does R have any hook that is executed on `error()` _before_ the `longjmp()`? Otherwise I guess we have to find a way to just let the memory leak and avoid calling `FINALLY_FREE()` in these situations.

**Comment by szhorvat** [comment] 2022-01-12 07:56
@ntamas There's some useful info here: https://stackoverflow.com/q/37845012/695132  It is claimed that Rcpp has a solution to this issue (i.e. error occurring in callback to R), and some of the Rcpp internals implementing that are linked from the answer.

**Comment by ntamas** [comment] 2022-01-12 08:13
> I read it, but I still don't know what to be careful about. 

Short summary: all sorts of nasty things may happen if we are calling back into R from igraph _and_ we have any stack-allocated pointers in the finally stack, unless we prevent R from `longjmp()`ing back to the top level.

The solution from Rcpp is simply to wrap the call in an R `tryCatch()` construct, which catches errors and returns them back to the user as a special object of class `condition`:

```
> tryCatch(sum(c("a", "b")), error=identity)
<simpleError in sum(c("a", "b")): invalid 'type' (character) of argument>
> x <- tryCatch(sum(c("a", "b")), error=identity)
> class(x)
[1] "simpleError" "error"       "condition"
```

That's something we can also do, but it does come with some performance implications.

**Closed** 2022-01-12 09:54 UTC
Labels: bug, high
