### ISSUE TITLE
Adding a program to existing igraph package

### ISSUE THREAD

**Issue by proj786** [igraph/rigraph#149] opened 2016-04-19 08:30 UTC
Hello,
 I am trying to add a function in igraph package. I created a simple c mycheck program in igraph/src directory and corressponding R funtion which called the mycheck program in igraph/R directory.

**mycheck.c file**
void mycheck()
{
printf("Hello, this is mycheck file");
}

**mycheck.r file**
# ' @export

mycheck1 <- function() {
.Call("mycheck")
}
We have made following modification:
  1)  Added "mycheck.r" in collate field of igraph/DESCRIPTION file.
  2)  Exported "mycheck1()"  , so that export(mycheck1) is included in igraph/NAMESPACE.
After these two modifications, when I called:
igraph::mycheck1()
Error is:  
Error in base::.Call(.Name, ...):
  "mycheck" not resolve from current namespace (igraph)

All the function that are in igraph/src directory have c interface in "rinterface.c" file, how can my function's interface will be avilable in "rinterface.c".

Kindly explain the steps that are required or if any step is missing.

**Comment by gaborcsardi** [comment] 2016-05-14 00:38
Maybe you did not install the new package, or loaded an old version? Or you did not recompile it? Anyway, hard to know, as I don't have a reproducible example of what you did.

**Comment by szhorvat** [comment] 2022-01-10 18:37
Closing, since this is not a bug report. If you still have questions, feel free to post on the forum at https://igraph.discourse.group/

**Closed by szhorvat** 2022-01-10 18:37 UTC
