### ISSUE TITLE
Fortran runtime error when using authority_score()

### ISSUE THREAD

**Issue by cpfaff** [igraph/rigraph#299] opened 2018-10-04 11:25 UTC
This example:

```R
require("igraph")
# Generate some test data
g <- make_ring(10, directed=FALSE)

authority_score(g)
```

Gives me a crash:

```
Fortran runtime error: Insufficient number of elements in TARRAY.
```

Sessioninfo:

```R
R version 3.5.1 (2018-07-02)                                                                                                                                                                     
Platform: x86_64-pc-linux-gnu (64-bit)                                                                                                                                                           
Running under: Arch Linux                                                                                                                                                                        

Matrix products: default
BLAS: /usr/lib/R/lib/libRblas.so
LAPACK: /usr/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C                                                                                                                                                     
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8                                                                                                                                           
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtils_11.0.1     colorout_1.2-0       devtools_1.13.6     
[4] RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
[1] compiler_3.5.1 withr_2.1.2    memoise_1.1.0  digest_0.6.17  
```

Fortran: gcc-fortran 8.2.1

**Comment by cpfaff** [comment] 2018-10-17 07:05
I tried also older versions of igraph from the archive on cran. The last two before the current. I also tried it with an older versions of gcc-fortran installed on my computer (8.1.1). This all has no effect. I get the same error.

**Comment by cpfaff** [comment] 2018-10-17 07:18
So what else could cause it? Some input would be great. I would help out and try things if I can.

**Comment by ntamas** [comment] 2018-10-20 13:58
Investigation in igraph/igraph#1121 shows that this is likely an R-specific issue; more precisely, it happens only when trying to install `igraph` in Microsoft R Open. I leave it up to @gaborcsardi to decide whether Microsoft R Open is to be supported officially and whether this issue is worth examining further.

**Comment by tiagobrc** [comment] 2019-08-25 16:19
having the same issue, is there any known solution? Thanks

**Comment by corriebar** [comment] 2020-04-16 14:22
I've encountered the same error and I installed `igraph` from CRAN (as far as I remember). Tried reinstalling, installing from github, same error.
Sessioninfo:
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 19.10

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] igraph_1.2.5

loaded via a namespace (and not attached):
[1] compiler_3.6.3  magrittr_1.5    tools_3.6.3     packrat_0.5.0   pkgconfig_2.0.3
```
Fortran Version used seems to be gfortran-9.
Any idea on how to fix this?

**Comment by szhorvat** [comment] 2022-04-01 12:55
@corriebar Can you try with the latest version, 1.3.0?

**Comment by ntamas** [comment] 2022-11-03 00:27
Works for me with the latest igraph version (1.3.5). Also, I don't think that Microsoft R Open is officially supported so closing this for the time being. Feel free to reopen if you can reproduce the issue with igraph 1.3.5 or later in a stock version of R.

**Closed by ntamas** 2022-11-03 00:27 UTC
