### ISSUE TITLE
problem installing igraph

### ISSUE THREAD

**Issue by Flu09** [igraph/rigraph#1188] opened 2024-02-03 15:07 UTC
I cannot upgrade igraph and it is preventing me from installing tidygraph and ggraph

devtools::install_github("igraph/rigraph")

vendor/cigraph/src/io/graphml.c:46:10: fatal error: libxml/globals.h: No such file or directory
   46 | #include <libxml/globals.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:191: vendor/cigraph/src/io/graphml.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/home/sherinepc/R/x86_64-pc-linux-gnu-library/4.3/igraph’
* restoring previous ‘/home/sherinepc/R/x86_64-pc-linux-gnu-library/4.3/igraph’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpWPv1rx/file4d5c84cab6583/igraph_2.0.1.9002.tar.gz’ had non-zero exit status
  
  
  
  
  
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Africa/Cairo
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] miniUI_0.1.1.1    compiler_4.3.2    promises_1.2.1    Rcpp_1.0.12       stringr_1.5.1     callr_3.7.3      
 [7] later_1.3.2       yaml_2.3.8        fastmap_1.1.1     mime_0.12         R6_2.5.1          curl_5.2.0       
[13] knitr_1.45        htmlwidgets_1.6.4 desc_1.4.3        profvis_0.3.8     shiny_1.8.0       rlang_1.1.3      
[19] cachem_1.0.8      stringi_1.8.3     httpuv_1.6.14     xfun_0.41         fs_1.6.3          pkgload_1.3.4    
[25] memoise_2.0.1     cli_3.6.2         magrittr_2.0.3    ps_1.7.6          processx_3.8.3    digest_0.6.34    
[31] rstudioapi_0.15.0 xtable_1.8-4      remotes_2.4.2.1   devtools_2.4.5    lifecycle_1.0.4   vctrs_0.6.5      
[37] evaluate_0.23     glue_1.7.0        urlchecker_1.0.1  sessioninfo_1.2.2 pkgbuild_1.4.3    rmarkdown_2.25   
[43] purrr_1.0.2       tools_4.3.2       usethis_2.2.2     ellipsis_0.3.2    htmltools_0.5.7  

sudo apt install libglpk-dev libgmp-dev libxml2-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libgmp-dev is already the newest version (2:6.2.1+dfsg-3ubuntu1).
libgmp-dev set to manually installed.
libglpk-dev is already the newest version (5.0-1).
libxml2-dev is already the newest version (2.9.13+dfsg-1ubuntu0.3).
The following packages were automatically installed and are no longer required:
  libflashrom1 libftdi1-2 libllvm13 wmdocker
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.

**Comment by szhorvat** [comment] 2024-02-03 18:00
Most likely the same as #1181 (i.e. bad quoting of the libxml2 include path). If you can't verify this, please post the compilation command from just before the error, so we can check.

**Comment by szhorvat** [comment] 2024-02-04 10:51
Duplicate of #1181

**Closed by szhorvat** 2024-02-04 10:51 UTC

**Comment by Flu09** [comment] 2024-02-05 12:15
>UPPORT -DHAVE_GFORTRAN=1 -D_GNU_SOURCE=1 -I'/home/sherinepc/R/x86_64-pc-linux-gnu-library/4.3/cpp11/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-H0vbME/r-base-4.3.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c vendor/cigr    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-H0vbME/r-base-4.3.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c vendor/cigraph/src/io/graphml.c -o vendor/cigraph/src/io/graphml.o
vendor/cigraph/src/io/graphml.c:46:10: fatal error: libxml/globals.h: No such file or directory
   46 | #include <libxml/globals.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:191: vendor/cigraph/src/io/graphml.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/home/sherinepc/R/x86_64-pc-linux-gnu-library/4.3/igraph’
* restoring previous ‘/home/sherinepc/R/x86_64-pc-linux-gnu-library/4.3/igraph’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpWPv1rx/file4d5c8520ae362/igraph_2.0.1.9004.tar.gz’ had non-zero exit statusaph/src/io/edgelist.c -o vendor/cigraph/src/io/edgelist.o
gcc -I"/usr/share/R/include" -DNDEBUG -DUSING_R -I. -Ivendor -Ivendor/cigraph/src -Ivendor/cigraph/include -Ivendor/cigraph/vendor -I"/home/sherinepc/anaconda3/include/libxml2 -I/home/sherinepc/anaconda3/include" -DNDEBUG -DNTIMER -DNPRINT -DINTERNAL_ARPACK -DIGRAPH_THREAD
c/io/graphml.c:46:10: fatal error: libxml/globals.h: No such file or directory
   46 | #include <libxml/globals.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:191: vendor/cigraph/src/io/graphml.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/home/sherinepc/R/x86_64-pc-linux-gnu-library/4.3/igraph’
* restoring previous ‘/home/sherinepc/R/x86_64-pc-linux-gnu-library/4.3/igraph’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpWPv1rx/file4d5c8520ae362/igraph_2.0.1.9004.tar.gz’ had non-zero exit status

**Comment by szhorvat** [comment] 2024-02-05 13:19
As a workaround, deactivate all conda environments before installing igraph. See the thread about this on https://igraph.discourse.group

**Comment by Flu09** [comment] 2024-02-06 22:34
problem solved by and running install.packages("igraph") in R and not Rstudio.
