### ISSUE TITLE
In install.packages("igraph") :   installation of package ‘igraph’ had non-zero exit status

### ISSUE THREAD

**Issue by jderry** [igraph/rigraph#230] opened 2017-10-06 20:20 UTC
foreign-graphml.c: In function ‘igraph_write_graph_graphml’:
foreign-graphml.c:1408:46: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "<graphml xmlns=\"" GRAPHML_NAMESPACE_URI "\"\n");
                                              ^~~~~~~~~~~~~~~~~~~~~
foreign-graphml.c:1412:59: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "         xsi:schemaLocation=\"" GRAPHML_NAMESPACE_URI "\n");
                                                           ^~~~~~~~~~~~~~~~~~~~~
foreign-graphml.c:1414:38: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "         " GRAPHML_NAMESPACE_URI "/1.0/graphml.xsd\">\n");
                                      ^~~~~~~~~~~~~~~~~~~~~
/usr/lib/R/etc/Makeconf:132: recipe for target 'foreign-graphml.o' failed
make: *** [foreign-graphml.o] Error 1
ERROR: compilation failed for package ‘igraph’

**Comment by Norali81** [comment] 2017-10-13 10:44
I have the same issue

**Comment by gaborcsardi** [comment] 2017-10-13 11:06
Duplicate of #213, #220, #226

**Closed by gaborcsardi** 2017-10-13 11:06 UTC
