### ISSUE TITLE
igraph failing to compile due to missing libicui18n.so.58 (Fedora)

### ISSUE THREAD

**Issue by vhcandido** [igraph/rigraph#274] opened 2018-05-22 01:59 UTC
Hi, I'm having an issue when installing igraph via `install.packages('igraph')`
and `devtools::install_github("igraph/rigraph")`.

It says it's unable to load `libicui18n.so.58` however I have `libicu` and `libicu-devel` installed.

> Error: package or namespace load failed for ‘igraph’ in dyn.load(file, DLLpath = DLLpath, ...):
> unable to load shared object '.../R/x86_64-pc-linux-gnu-library/3.4/igraph/libs/igraph.so':
>  libicui18n.so.58: cannot open shared object file: No such file or directory
>Error: loading failed
>Execution halted
>ERROR: loading failed
> ...
>Warning message:
>In install.packages("igraph") :
>  installation of package ‘igraph’ had non-zero exit status

R 3.4.3 | Fedora 23 (4.8.13-100.fc23.x86_66)

**Comment by jlblancopastor** [comment] 2018-08-03 10:07
Same problem here.

**Comment by mawds** [comment] 2018-10-17 08:17
I too got this problem.  I tracked it down to an anaconda python being in the path.  It looked like this was being included as header directories (`-I`) when igraph installed.

Removing anaconda from the path fixed it.

**Comment by wayne-emery** [comment] 2018-10-17 18:38
Didn't work for me. Could you be more specific?

**Comment by mawds** [comment] 2018-10-18 07:00
Anaconda adds its path to your directory search path when it is installed, by adding a line to ~/.bashrc.  I commented this out, and igraph then installed (it also needed to be commented out for igraph to run).

I noticed that an anaconda path was being included in the `-I` flag on the gcc lines as igraph was installing; that's what made me try removing it from my path.  

Having made the change to .bashrc, you'll need to open a new terminal window; it's only read when you start a new shell.

That's the only change I made.

**Comment by ChemiKyle** [comment] 2019-05-14 23:56
I had this same issue with a different library and using Debian testing (buster), but this is the closest result I found after much searching, so I'll post my solution here for anyone else running into issues.

Commenting out the path in my `.bashrc` did not work, I had to create `~/.R/Makevars` and enter the line `CXX=g++-8` (you'll likely need to adjust for your g++ version).

**Comment by kojikoji** [comment] 2019-06-01 23:27
The same problem was discussed [here](https://github.com/LinkageIO/Minus80/issues/3).
So, I solved this issue by installing ICU 58 as below:
```
wget https://github.com/unicode-org/icu/archive/release-58-3.tar.gz
tar xvzf release-58-3.tar.gz
cd icu-release-58-3/icu4c/source
./configure
make
make install
```

**Comment by genecell** [comment] 2020-11-13 06:32
> The same problem was discussed [here](https://github.com/LinkageIO/Minus80/issues/3).
> So, I solved this issue by installing ICU 58 as below:
> 
> ```
> wget https://github.com/unicode-org/icu/archive/release-58-3.tar.gz
> tar xvzf release-58-3.tar.gz
> cd icu-release-58-3/icu4c/source
> ./configure
> make
> make install
> ```

Thanks! this works for me!

**Comment by HUNNNGRY** [comment] 2021-03-06 15:20
> Anaconda adds its path to your directory search path when it is installed, by adding a line to ~/.bashrc. I commented this out, and igraph then installed (it also needed to be commented out for igraph to run).
> 
> I noticed that an anaconda path was being included in the `-I` flag on the gcc lines as igraph was installing; that's what made me try removing it from my path.
> 
> Having made the change to .bashrc, you'll need to open a new terminal window; it's only read when you start a new shell.
> 
> That's the only change I made.

For some reason R compile packages use files found in anaconda/bin dir if anaconda was installed, and I commented in "PATH=~/anaconda3/bin/:$PATH " in  .bashrc  to remove conda env in PATH and it worked, the r package XML was installed successfully.

**Comment by szhorvat** [comment] 2022-04-01 13:01
It seems that this is typically caused by a conda environment being active. 

Deactivate all environment using `conda deactivate` and try again.

Closing now, please re-open if the issue comes back.

**Closed by szhorvat** 2022-04-01 13:01 UTC
