### ISSUE TITLE
Inconsistency in modularity function

### ISSUE THREAD

**Issue by BurhanSabuwala** [igraph/rigraph#480] opened 2021-09-26 11:03 UTC
The value of modularity obtained using igraph for a directed graph is inconsistent with that hand-calculated value or the value obtained using networkx.

For example, consider the following code.
```{R}
my_graph <- graph_from_adjacency_matrix(cbind(c(0,1,0,0,0),c(1,0,0,0,0),c(0,0,0,1,0), c(0,0,0,0,1), c(1,0,1,0,0)), 'directed')
print(modularity(my_graph, c(1,1,2,2,2))
```
`[1] 0.3194444`

For the same network, we get a different result using networkx.
```
import networkx as nx
G = nx.DiGraph()
G.add_edge(1,2);G.add_edge(2,1)
G.add_edge(4,3); G.add_edge(5,4); G.add_edge(1,5); G.add_edge(3,5)
nx.community.modularity(G, [[1,2],[3,4,5]])
```
`0.33333333333333337`

The value obtained from networkx is consistent with the formula of modularity Q = 1/m * sum_ij(A_ij - k_i_out * k_j_in / (m), delta(i,j)) for the directed graph.

**Comment by szhorvat** [comment] 2021-09-26 11:09
This is not a bug.

If you check the documentation, you will see that the formula given there is for undirected graphs. The result is consistent with that formula, i.e. edge directions are ignored.

Directed modularity is implemented in the C core and will be included in a future version of the R interface.

**Closed by szhorvat** 2021-09-26 11:09 UTC

**Comment by BurhanSabuwala** [comment] 2021-09-26 13:36
Thank you very much!
