### ISSUE TITLE
Intermittent NaN's in layout_as_tree()

### ISSUE THREAD

**Issue by wlandau** [igraph/rigraph#215] opened 2017-07-31 00:17 UTC
Occasionally, `igraph::layout_as_tree()` returns `NaN`'s as `y` coordinates. The issue is difficult tor reproduce, but the graph in datastorm-open/visNetwork#184 sometimes does it.

**Comment by wlandau-lilly** [comment] 2017-07-31 03:39
Ha...so I just realized that I had no business imposing a tree layout on a non-tree. I won't object if you close this issue, but I will leave it open in case you want to sanitize user input for this edge case.

**Comment by wlandau** [comment] 2017-07-31 03:40
Ha...so I just realized that I had no business imposing a tree layout on a non-tree. I won't object if you close this issue, but I will leave it open in case you want to sanitize user input for this edge case.

**Comment by wlandau** [comment] 2021-10-12 01:45
IIRC I think it was random.

**Comment by szhorvat** [comment] 2022-01-10 19:42
Closing this since the underlying function got multiple fixes in the C core, and we don't have a reproducing example. The fixes are available in the dev version (to become 1.3).

**Closed by szhorvat** 2022-01-10 19:42 UTC
